-- ao_kgp
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8000146,'М-Н ГЕРIВКА');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8000260,'М-Н ВИЗИТ /БУРКА/');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8000336,'М-Н МАЯК РОМНЫ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8000374,'М-Н ЛОТОС РОМНЫ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8000414,'М-Н МАГНОЛИЯ РОМНЫ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8000957,'М-Н ОБЖОРКА-2 АХТЫРКА');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8001137,'М-Н МЯСОКОМБИНАТ ВОРОЖБА');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8001161,'М-Н ТРОЯНДА-1');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460037,'М-Н "КОШИК-МАРКЕТ" ЦУМ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (2639022,'М-Н PRESS-ТИЖ ЛОТОС');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (2778492,'М-Н "КОШИК" ЗАСУМСКАЯ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460341,'М-Н САМ МАРКЕТ 21');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460365,'М-Н ПРОДУКТЫ /СПД ТИШИК/');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460288,'М-Н ПРОДУКТЫ /СПД МАТЮШЕНКО/');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460364,'М-Н САМ МАРКЕТ КОВПАКА');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460366,'М-Н ПРОДУКТЫ /ПУЗЬ/');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460344,'М-Н ПРОДУКТЫ ПР.КУРСКИЙ /ЛЕВЧЕНКО/');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (3218628,'М-Н МАНДАРИН ЧЕРЕПИНА');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460216,'М-Н САМ МАРКЕТ ЛУШПЫ 7');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460123,'М-Н 43 Я.МУДРОГО');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460026,'М-Н САМ МАРКЕТ ОКЕАН');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (2329092,'М-Н НАШ МАРКЕТ СКД');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (2523306,'М-Н ВЕСЕЛКА КОВПАКА');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460184,'М-Н "AMBAR" ПРОКОФЬЕВСКИЙ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460369,'КИОСК ДЕТСК. БОЛЬНИЦА /ЧАЙКА/');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (2111253,'М-Н ЛУЧ-1 ХАРЬКОВСКАЯ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460559,'М-Н ПРОДУКТЫ ЧАПАЕВА /ЛИТВИНЕНКО/');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8002059,'М-Н КАПРИЗ-5 САМОТОЕВКА');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8002512,'КИОСК АЙСБЕРГ /ГРОБОВ/');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8003099,'М-Н КАПРИЗ-7 МАРКЕТ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460990,'М-Н ГАСТРОНОМЧИК СОБОРНАЯ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460996,'М-Н НАШ МАРКЕТ КУРСКИЙ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8461045,'М-Н ПРОДУКТЫ ЗАЛИВНАЯ /ШАФОРОСТ/');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8461101,'М-Н "AMBAR" СКД');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8461128,'М-Н "ГАСТРОНОМЪ" ПОКРОВСКАЯ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8461130,'М-Н ПРОДУКТЫ КОРОТЧЕНКО /ЯНЧЕНКО/');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8460186,'М-Н "КОШИК-МАРКЕТ" РОСИНКА');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8003807,'М-Н "ФРЕШ" РОМНЫ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (3210441,'М-Н "КОШИК-МАРКЕТ" ТЦ АТРИУМ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8461311,'М-Н МОЛОЧНЫЙ-1 СУМСЕЛЬМАШ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8461416,'М-Н МОЛОЧНЫЙ-1 ШЕВЧЕНКО');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (2937614,'М-Н "КОШИК-МАРКЕТ" ТРОИЦКИЙ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8461441,'М-Н АЖИОТАЖ ИЛЬИНСКАЯ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (20555,'М-Н ПРОДУКТЫ 223');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (1116763,'М-Н САМ МАРКЕТ ЛУШПЫ 39');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8005178,'М-Н МАЛИНА РОМНЫ');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8461717,'М-Н КОМОРА ПРОКОФЬЕВА');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8461035,'М-Н КЛУНОК ПРОКОФЬЕВА');
INSERT INTO ao_kgp (KGp,NGrpol) VALUES (8005294,'М-Н "КОШИК-МАРКЕТ" АХТЫРКА');